site_name: Lock View Documentation
site_url: https://materialfoundry.github.io/LockView/
nav:
  - Home: index.md
  - Control Buttons: controlButtons.md
  - Viewbox: viewbox.md
  - Scene Config:
    - Scene Config: sceneConfig/sceneConfig.md
    - Locks: sceneConfig/locks.md
    - Autoscale: sceneConfig/autoscale.md
    - Sidebar: sceneConfig/sidebar.md
    - Hide UI Elements: sceneConfig/hideElements.md
    - Force Initial View: sceneConfig/initialView.md
  - Module Settings: 
    - Module Settings: moduleSettings/moduleSettings.md
    - User Configurator: moduleSettings/userConfigurator.md
    - Scene Configurator: moduleSettings/sceneConfigurator.md
    - Clone View Configurator: moduleSettings/cloneViewConfigurator.md
    - Control Buttons Configurator: moduleSettings/controlButtonsConfigurator.md
    - Hotkeys: moduleSettings/hotkeys.md
  - Example Configurations: exampleConfigurations.md
    
theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  
  favicon: img/icon.ico
  logo: img/MaterialFoundry.png

  features:
    - navigation.tracking
    - navigation.tabs
    - toc.integrate
    - navigation.top

plugins:
  - search

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/3hd4G6TkmA
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/materialfoundry

extra_css:
  - style.css